name = "membersite-leosiqra"
main = "./src/index.js"
compatibility_date = "2025-04-19"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/dashboard", "/admin*", "/login", "/register", "/profile", "/membership/*", "/auth/*"]

[[d1_databases]]
binding = "DB"
database_name = "membersite_leosiqra_db"
database_id = "a04174cd-6f44-4403-bec1-6ca3dddb1a9c"

[[r2_buckets]]
binding = "FILES"
bucket_name = "membersite-leosiqra-assets"

[vars]
APP_NAME = "Membersite Leosiqra"
PUBLIC_APP_URL = "http://127.0.0.1:8787"
R2_PUBLIC_BASE_URL = ""
